/*
 */
package game;

/**
 * Displays the user's current achievements (medals) status
 * 
 * @author Hailey Pong
 */
public class Achievement extends javax.swing.JFrame {

    private Player player; // Variable to store the current Player object

    /**
     * Creates new form game
     */
    public Achievement(Player player) {
        initComponents();           
        this.player = player; // Set the current Player object   
        user_id.setText(player.getId());
        getAchievements();
    }

    /**
     * Changes icon according to the user's current achievements
     */
    private void getAchievements () {
        Boolean[] achievement = player.getAchievement();
        
        if (achievement != null) {
            // bronze
            if (achievement[0] == true) { 
                bronzeMedal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bronze.png")));
            } else {
                    bronzeMedal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bronzeLock.png")));            
            }

            // silver
            if (achievement[1] == true) {  
                silverMedal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/silver.png")));
            } else {
                 silverMedal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/silverLock.png")));            
            }
            // gold
            if (achievement[2] == true) {  
                goldMedal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gold.png")));
            }  else {
                goldMedal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/goldLock.png")));            
            }
        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bronze = new javax.swing.JLabel();
        bronzeMedal = new javax.swing.JLabel();
        silver = new javax.swing.JLabel();
        goldMedal = new javax.swing.JLabel();
        gold = new javax.swing.JLabel();
        silverMedal = new javax.swing.JLabel();
        user_id = new javax.swing.JLabel();
        mainbutton = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 600));

        jPanel1.setBackground(new java.awt.Color(254, 253, 237));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));

        bronze.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bronze.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bronze.setText("BRONZE");

        bronzeMedal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bronzeLock.png"))); // NOI18N

        silver.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        silver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        silver.setText("SILVER");

        goldMedal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/goldLock.png"))); // NOI18N

        gold.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        gold.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gold.setText("GOLD");

        silverMedal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/silverLock.png"))); // NOI18N

        user_id.setBackground(new java.awt.Color(254, 253, 237));
        user_id.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        user_id.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        user_id.setText("USERID");

        mainbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        mainbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainbuttonMouseClicked(evt);
            }
        });

        jLabel2.setText("Back to Main");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trophy.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(mainbutton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(user_id, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bronze, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bronzeMedal, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(silverMedal, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(silver, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(goldMedal, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gold, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(mainbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(user_id, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addGap(95, 95, 95)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bronzeMedal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goldMedal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(silverMedal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gold, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(silver, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bronze, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(201, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 986, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1000, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * returns to main menu
     * @param evt 
     */
    private void mainbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainbuttonMouseClicked
        Menu main = new Menu(player);
        main.setVisible(true);
        dispose();
    }//GEN-LAST:event_mainbuttonMouseClicked
            

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bronze;
    private javax.swing.JLabel bronzeMedal;
    private javax.swing.JLabel gold;
    private javax.swing.JLabel goldMedal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mainbutton;
    private javax.swing.JLabel silver;
    private javax.swing.JLabel silverMedal;
    private javax.swing.JLabel user_id;
    // End of variables declaration//GEN-END:variables
}
