
package game;
import javax.swing.table.DefaultTableModel;
import java.util.*;

/**
 * Easy interaction 
 * @author kareena.sen
 * @author Simran Kullar (Added changes to the EasyHighScoreTable constructor -- called saveHighScoresCSV method)
 */
public class EasyHighScoreTable extends javax.swing.JFrame implements Comparator<Integer> {
    
    private String[][] easyArray;
    private Player currentPlayer;
    /**
     * Creates new form HighScoreTable
     */   
    public EasyHighScoreTable(Player currentPlayer) {
        // Call initComponents method to setup the JFrame components
        initComponents();
        this.currentPlayer = currentPlayer;
        // Retrieve and prepare the data necessary to display the Easy High Scores
        getEasyData();
    
        // Initialize a LinkedList to hold Player objects for the leaderboard
        LinkedList<Player> playersList = new LinkedList<>();
        // Iterate over the dataList static member of the Data class.
        for (Player data : Data.dataList) {
            // Create new Player objects using the information retrieved from the dataList
            // The Player constructor is assumed to take the ID, pin, high scores array,
            // progress, and achievements array as parameters
            Player players= new Player(data.getId(), data.getPin(), data.getHighscore(), data.getProg(), data.getAchievement());

            // Add each new Player object to the playersList LinkedList.
            playersList.add(players);
        }
    
        // Initialize the leaderboard with the players list
        Leaderboard leaderboard = new Leaderboard(playersList);
    
        // Save the high scores to a CSV file
        // saveHighScoresToCSV takes filename and level index as parameters
        leaderboard.saveHighScoresToCSV("highscoresEasy.csv", 0);
    
        // Update the high score table in the UI
        updateEasyHSTable();
         // Set player to specified player
    }
    
    
    @Override
    public int compare(Integer a, Integer b){
        if(a > b){
            return 1;
        }
        else if(a < b){
            return -1;
        }
        else{
            return 0;
        }
    }
    
    
    private void getEasyData() {
        Map <String, Integer> easyScoresDict = new HashMap<>();
        LinkedHashMap <String, Integer> sortedEasyScores = new LinkedHashMap();
        ArrayList <Integer> placeHolderList = new ArrayList<>();
        for(int i = 0; i < Data.dataList.size(); i++) {
            easyScoresDict.put(Data.dataList.get(i).getId(), Data.dataList.get(i).getHighscore()[0]); 
        }
        for(Map.Entry<String, Integer> entry : easyScoresDict.entrySet()){
            placeHolderList.add(entry.getValue());
        }
        Collections.sort(placeHolderList, Collections.reverseOrder());
        for(int num : placeHolderList){
            for(Map.Entry<String, Integer> entry : easyScoresDict.entrySet()){
                if(entry.getValue().equals(num)){
                    sortedEasyScores.put(entry.getKey(), num);
                }
            }
        }
        easyArray = new String [2][sortedEasyScores.size()];
        Set<String> keys = sortedEasyScores.keySet();
        int j = 0;
        for (String key : keys){
            easyArray[0][j] = key;
            easyArray[1][j] = String.valueOf(sortedEasyScores.get(key));
            j++;
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEasyModeHighScoreTable = new javax.swing.JTable();
        jEasyModeHighScoreLabel = new javax.swing.JLabel();
        jEasyModeButton = new javax.swing.JButton();
        jMedButton = new javax.swing.JButton();
        jHardModeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jEasyModeMenuBar = new javax.swing.JMenuBar();
        jEasyModeMenuBarLabel = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jEasyModeHighScoreTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"user1", "user1_score"},
                {"user2", "user2_score"},
                {"user3", "user3_score"},
                {null, null}
            },
            new String [] {
                "User", "Top Highscores"
            }
        ));
        jScrollPane1.setViewportView(jEasyModeHighScoreTable);
        if (jEasyModeHighScoreTable.getColumnModel().getColumnCount() > 0) {
            jEasyModeHighScoreTable.getColumnModel().getColumn(1).setResizable(false);
        }

        jEasyModeHighScoreLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        jEasyModeHighScoreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jEasyModeHighScoreLabel.setText("Easy Mode High Score Table");

        jEasyModeButton.setBackground(new java.awt.Color(255, 102, 153));
        jEasyModeButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jEasyModeButton.setForeground(new java.awt.Color(255, 255, 255));
        jEasyModeButton.setText("Easy");

        jMedButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jMedButton.setForeground(new java.awt.Color(255, 51, 153));
        jMedButton.setText("Medium");
        jMedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMedButtonActionPerformed(evt);
            }
        });

        jHardModeButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jHardModeButton.setForeground(new java.awt.Color(255, 51, 153));
        jHardModeButton.setText("Hard");
        jHardModeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHardModeButtonActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fullheart.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fullheart.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fullheart.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fullheart.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fullheart.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fullheart.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fullheart.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fullheart.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel10.setText("Back to Menu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jEasyModeButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(318, 318, 318)
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jEasyModeHighScoreLabel)
                        .addGap(170, 170, 170)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jMedButton)
                        .addGap(18, 18, 18)
                        .addComponent(jHardModeButton)))
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel5))
                .addGap(178, 178, 178)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 284, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(354, 354, 354))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(916, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(47, 47, 47)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEasyModeButton)
                    .addComponent(jMedButton)
                    .addComponent(jHardModeButton))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(76, 76, 76)
                        .addComponent(jEasyModeHighScoreLabel)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jLabel1)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel3)
                                .addGap(60, 60, 60))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(175, 175, 175)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addGap(40, 40, 40))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel6)
                        .addGap(61, 61, 61)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(90, 90, 90))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(291, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addGap(262, 262, 262)))
        );

        jEasyModeMenuBarLabel.setText("Capital Chain - Easy Mode High Scores Table ");
        jEasyModeMenuBar.add(jEasyModeMenuBarLabel);

        setJMenuBar(jEasyModeMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     /**
     * Normal mode high scores
     * @param evt 
     */
    private void jMedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMedButtonActionPerformed
       MediumHighScoreTable medLead = new MediumHighScoreTable(currentPlayer);
       medLead.setVisible(true);
       dispose();
    }//GEN-LAST:event_jMedButtonActionPerformed

    /**
     * Hard mode high scores
     * @param evt 
     */
    private void jHardModeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHardModeButtonActionPerformed
       HardHighScoreTable hardLead = new HardHighScoreTable(currentPlayer);
       hardLead.setVisible(true);
       dispose();
    }//GEN-LAST:event_jHardModeButtonActionPerformed
    
    /**
     * Main menu 
     * @param evt 
     */
    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        Menu menu = new Menu(currentPlayer);
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void updateEasyHSTable() {
    // Create a new DefaultTableModel
    DefaultTableModel model = new DefaultTableModel();
    
    // Add columns to the model
    model.addColumn("User");
    model.addColumn("Top Highscores");
    
    // Add data from easyArray to the model
    for (int i = 0; i < easyArray[0].length; i++) {
        model.addRow(new Object[]{easyArray[0][i], easyArray[1][i]});
    }
    
    // Set the new model to the jEasyModeHighScoreTable
    jEasyModeHighScoreTable.setModel(model);
}


/**
 * Private variables
 */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jEasyModeButton;
    private javax.swing.JLabel jEasyModeHighScoreLabel;
    private javax.swing.JTable jEasyModeHighScoreTable;
    private javax.swing.JMenuBar jEasyModeMenuBar;
    private javax.swing.JMenu jEasyModeMenuBarLabel;
    private javax.swing.JButton jHardModeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jMedButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
