package game;

/**
 * InstructorDashboard class represents a JFrame displaying instructor's dashboard.
 * It fetches data from Data class and populates it into a table.
 * It also sets the appearance of the table.
 * @author kareena.sen
 */
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import java.util.HashSet;
import java.util.Set;
import java.util.ArrayList;
import java.util.List;

public class InstructorDashboard extends javax.swing.JFrame {

    /**
     * Creates a new instance of InstructorDashboard.
     */
    public InstructorDashboard() {
        initComponents(); // Initialize GUI components
        iterateDataList(); // Fetch and populate data into the table
        
        // Make the table background transparent
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        jStudentInfoTable.setOpaque(false);
        
        // Set grid lines color to make them less visible
        jStudentInfoTable.setGridColor(new Color(255, 255, 255, 100)); // Set the grid lines color to white with 100 alpha (more transparent)
    }
    
    
    /**
     * Iterates through the dataList and populates the table with student information.
     */

private void iterateDataList() {
    // Create a Set to keep track of processed student IDs
    Set<String> processedIds = new HashSet<>();
    
    // Create a list to store unique student information
    List<String[]> uniqueDataList = new ArrayList<>();

    for (int i = 0; i < Data.dataList.size(); i++) {
        String currentId = Data.dataList.get(i).getId();
        
        // Check if the current ID has already been processed
        if (!processedIds.contains(currentId)) {
            processedIds.add(currentId);
            
            // Populate dataArray with student information
            String[] studentData = new String[5];
            studentData[0] = currentId;
            studentData[1] = String.valueOf(Data.dataList.get(i).getHighscore()[0]);
            studentData[2] = String.valueOf(Data.dataList.get(i).getHighscore()[1]);
            studentData[3] = String.valueOf(Data.dataList.get(i).getHighscore()[2]);
            studentData[4] = String.valueOf(Data.dataList.get(i).getProg());
            
            // Add unique student information to the list
            uniqueDataList.add(studentData);
        }
    }

    // Convert uniqueDataList to a 2D array
    String[][] dataArray = uniqueDataList.toArray(new String[0][]);

    // Define column names
    String[] columnNames = {"Student", "Easy", "Medium", "Hard", "Current Level"};

    // Create a new DefaultTableModel with the dataArray and columnNames
    DefaultTableModel model = new DefaultTableModel(dataArray, columnNames);

    // Set the model to the jStudentInfoTable
    jStudentInfoTable.setModel(model);
}
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jExitButton = new javax.swing.JButton();
        jLoginButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jStudentInfoTable = new javax.swing.JTable();
        jInstructorDashboardMenuBar = new javax.swing.JMenuBar();
        jInstructorDashMenuLabel = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jExitButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jExitButton.setForeground(new java.awt.Color(102, 0, 204));
        jExitButton.setText("Exit");
        jExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitButtonActionPerformed(evt);
            }
        });

        jLoginButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLoginButton.setForeground(new java.awt.Color(102, 0, 204));
        jLoginButton.setText("Logout");
        jLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButtonActionPerformed(evt);
            }
        });

        jStudentInfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student", "Easy", "Medium", "Hard", "Current Level"
            }
        ));
        jScrollPane1.setViewportView(jStudentInfoTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLoginButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jExitButton)))
                .addGap(114, 114, 114))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLoginButton)
                    .addComponent(jExitButton))
                .addGap(97, 97, 97))
        );

        jInstructorDashMenuLabel.setText("Capital Chain - Instructor Dashboard");
        jInstructorDashboardMenuBar.add(jInstructorDashMenuLabel);

        setJMenuBar(jInstructorDashboardMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButtonActionPerformed
        Login logout = new Login();
        logout.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLoginButtonActionPerformed

    /**
     * exist the program
     * @param evt 
     */
    private void jExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstructorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstructorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstructorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstructorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstructorDashboard().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jExitButton;
    private javax.swing.JMenu jInstructorDashMenuLabel;
    private javax.swing.JMenuBar jInstructorDashboardMenuBar;
    private javax.swing.JButton jLoginButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jStudentInfoTable;
    // End of variables declaration//GEN-END:variables
}
