
package game;

/**
 * Displays Level selections (easy, normal, hard) to the user and starts a new game when the user chooses difficulty
 * @author Hailey Pong
 */
public class Level extends javax.swing.JFrame {

    Player player;
    
    /**
     * Creates new form Menu
     * @Constructor
     * @param player 
     */
    public Level(Player player) {
        initComponents();
        this.player = player;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        easyMess = new javax.swing.JLabel();
        normMess = new javax.swing.JLabel();
        hardMess = new javax.swing.JLabel();
        hard = new javax.swing.JLabel();
        norm = new javax.swing.JLabel();
        easy = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mainBUtton = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(254, 253, 237));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Choose Your Level");

        easyMess.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        easyMess.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        easyMess.setText("PLAY EASY!");

        normMess.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        normMess.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        normMess.setText("PLAY NORMAL!");

        hardMess.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hardMess.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hardMess.setText("PLAY HARD!");

        hard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Hard.png"))); // NOI18N
        hard.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                hardHover(evt);
            }
        });
        hard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hardMode(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hardOut(evt);
            }
        });

        norm.setBackground(new java.awt.Color(254, 253, 237));
        norm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        norm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/normal.png"))); // NOI18N
        norm.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                normHover(evt);
            }
        });
        norm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                normMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                normOut(evt);
            }
        });

        easy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        easy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/easy.png"))); // NOI18N
        easy.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                easyHover(evt);
            }
        });
        easy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                easyMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                easyHoverOut(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("You need to complete previous level to play the next level");

        mainBUtton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        mainBUtton.setText("jLabel3");
        mainBUtton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainBUttonMouseClicked(evt);
            }
        });

        jLabel3.setText("Back to Main");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(easyMess, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(normMess, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(easy, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130)
                        .addComponent(norm, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(hard, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(hardMess, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(192, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(401, 401, 401)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(mainBUtton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(mainBUtton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hard, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(easy, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(norm, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(normMess)
                    .addComponent(hardMess)
                    .addComponent(easyMess))
                .addGap(191, 191, 191))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    /** 
     * Opens hard mode game
     * @param evt 
     */
    private void hardMode(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hardMode
        if (player.getProg() >= 2){
            GamePlay game = new GamePlay(2);
            Play play = new Play (player, game);
            play.setVisible(true);
            dispose();             
        }
        else {
            hardMess.setText("Complete Normal To Play");
        }
    }//GEN-LAST:event_hardMode

    /**
     * Opens normal
     * @param evt 
     */
    private void normMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_normMouseClicked
       if (player.getProg() >= 1){
            GamePlay game = new GamePlay(1);
            Play play = new Play (player, game);
            play.setVisible(true);
            dispose();             
        }
        else {
            normMess.setText("Complete Easy To Play");
        }
    }//GEN-LAST:event_normMouseClicked

    /**
     * Opens easy mode
     * @param evt 
     */
    private void easyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_easyMouseClicked
        GamePlay game = new GamePlay(0);
        Play play = new Play (player, game);
        play.setVisible(true);
        dispose();
    }//GEN-LAST:event_easyMouseClicked

    private void easyHover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_easyHover
        jLabel1.setText("Play Easy?");
    }//GEN-LAST:event_easyHover

    private void easyHoverOut(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_easyHoverOut
        jLabel1.setText("Choose Your Level");
    }//GEN-LAST:event_easyHoverOut

    private void normHover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_normHover
        jLabel1.setText("Play Normal?");
    }//GEN-LAST:event_normHover

    private void normOut(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_normOut
        jLabel1.setText("Choose Your Level");
    }//GEN-LAST:event_normOut

    private void hardHover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hardHover
        jLabel1.setText("Play Hard?");
    }//GEN-LAST:event_hardHover

    private void hardOut(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hardOut
        jLabel1.setText("Choose Your Level");
    }//GEN-LAST:event_hardOut

    private void mainBUttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainBUttonMouseClicked
        Menu menu = new Menu(player);
        menu.setVisible(true);
        dispose();    }//GEN-LAST:event_mainBUttonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel easy;
    private javax.swing.JLabel easyMess;
    private javax.swing.JLabel hard;
    private javax.swing.JLabel hardMess;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mainBUtton;
    private javax.swing.JLabel norm;
    private javax.swing.JLabel normMess;
    // End of variables declaration//GEN-END:variables
}
