
package game;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.LinkedList;
import java.util.Map;
import java.util.Set;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kareena.sen
 * @author Simran Kullar (Added changes to the MediumHighScoreTable constructor -- called saveHighScoresCSV method)
 */
public class MediumHighScoreTable extends javax.swing.JFrame{
    private Player currentPlayer;


    /**
     * Creates new form MediumHighScoreTable
     * @param currentPlayer 
     */
    public MediumHighScoreTable(Player currentPlayer) {
        // Call initComponents method to setup the JFrame components
        initComponents();
        this.currentPlayer = currentPlayer;
        
        // Initialize a LinkedList to hold Player objects for the leaderboard
        getMediumData();

        // Initialize players list for the leaderboard
        LinkedList<Player> playersList = new LinkedList<>();

        // Iterate over the dataList static member of the Data class
        for (Player data : Data.dataList) {
            
            // Create new Player objects using the information retrieved from the dataList
            // The Player constructor is assumed to take the ID, pin, high scores array,
            // progress, and achievements array as parameters
            Player players = new Player(data.getId(), data.getPin(), data.getHighscore(), data.getProg(), data.getAchievement());
            
            // Add each new Player object to the playersList LinkedList
            playersList.add(players);
        }
    
        // Initialize the leaderboard with the players list
        Leaderboard leaderboard = new Leaderboard(playersList);
    
        // Save the high scores to a CSV file
        // saveHighScoresToCSV takes filename and level index as parameters
        leaderboard.saveHighScoresToCSV("highscoresMedium.csv", 1);

        // Update the high score table in the UI
        updateMediumHSTable();
         // Set player to specified player
    }
    
    private String[][] mediumArray;
    
    public int compare(Integer a, Integer b) {
        if(a > b) {
            return 1;
        }
        else if(a < b) {
            return -1;
        }
        else {
            return 0;
        }
    }
    
    private void getMediumData() {
        Map <String, Integer> easyScoresDict = new HashMap<>();
        LinkedHashMap <String, Integer> sortedEasyScores = new LinkedHashMap();
        ArrayList <Integer> placeHolderList = new ArrayList<>();
        for(int i = 0; i < Data.dataList.size(); i++) {
            easyScoresDict.put(Data.dataList.get(i).getId(), Data.dataList.get(i).getHighscore()[1]); 
        }
        for(Map.Entry<String, Integer> entry : easyScoresDict.entrySet()){
            placeHolderList.add(entry.getValue());
        }
        Collections.sort(placeHolderList, Collections.reverseOrder());
        for(int num : placeHolderList){
            for(Map.Entry<String, Integer> entry : easyScoresDict.entrySet()){
                if(entry.getValue().equals(num)){
                    sortedEasyScores.put(entry.getKey(), num);
                }
            }
        }
        mediumArray = new String [2][sortedEasyScores.size()];
        Set<String> keys = sortedEasyScores.keySet();
        int j = 0;
        for (String key : keys){
            mediumArray[0][j] = key;
            mediumArray[1][j] = String.valueOf(sortedEasyScores.get(key));
            j++;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jMedModeHighScoreTable = new javax.swing.JTable();
        jMedButton = new javax.swing.JButton();
        jEasyButton = new javax.swing.JButton();
        jHardModeButton = new javax.swing.JButton();
        jMedModeHighScoreTableLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMedHighScoreMenuBar = new javax.swing.JMenuBar();
        jMediumMenuBarLabel = new javax.swing.JMenu();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"user1", "user1_score"},
                {"user2", "user2_score"},
                {"user3", "user3_score"},
                {null, null}
            },
            new String [] {
                "User", "User Score"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));

        jPanel1.setBackground(new java.awt.Color(251, 247, 186));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));

        jMedModeHighScoreTable.setBackground(new java.awt.Color(255, 204, 153));
        jMedModeHighScoreTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"user1", "user1_score"},
                {"user2", "user2_score"},
                {"user3", "user3_score"},
                {null, null}
            },
            new String [] {
                "User", "Top Highscores"
            }
        ));
        jScrollPane2.setViewportView(jMedModeHighScoreTable);

        jMedButton.setBackground(new java.awt.Color(255, 204, 102));
        jMedButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jMedButton.setForeground(new java.awt.Color(255, 255, 255));
        jMedButton.setText("Medium");

        jEasyButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jEasyButton.setForeground(new java.awt.Color(255, 153, 0));
        jEasyButton.setText("Easy");
        jEasyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEasyButtonActionPerformed(evt);
            }
        });

        jHardModeButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jHardModeButton.setForeground(new java.awt.Color(255, 153, 0));
        jHardModeButton.setText("Hard");
        jHardModeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHardModeButtonActionPerformed(evt);
            }
        });

        jMedModeHighScoreTableLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        jMedModeHighScoreTableLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMedModeHighScoreTableLabel.setText("Medium Mode High Score Table");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star.png"))); // NOI18N
        jLabel2.setText("jLabel1");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star.png"))); // NOI18N
        jLabel3.setText("jLabel1");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star.png"))); // NOI18N
        jLabel4.setText("jLabel1");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star.png"))); // NOI18N
        jLabel5.setText("jLabel1");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star.png"))); // NOI18N
        jLabel6.setText("jLabel1");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Back to Menu");
        jLabel8.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(265, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jEasyButton)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jMedButton)
                                .addGap(18, 18, 18)
                                .addComponent(jHardModeButton)))
                        .addGap(35, 35, 35))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(213, 213, 213)
                        .addComponent(jMedModeHighScoreTableLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(375, 375, 375)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEasyButton)
                    .addComponent(jMedButton)
                    .addComponent(jHardModeButton))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jMedModeHighScoreTableLabel)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)))
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2)
                        .addGap(187, 187, 187)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel6)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(87, 87, 87))
        );

        jMediumMenuBarLabel.setText("Capital Chain - Medium Mode High Scores Table");
        jMedHighScoreMenuBar.add(jMediumMenuBarLabel);

        setJMenuBar(jMedHighScoreMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Easy mode high scores
     * @param evt 
     */
    private void jEasyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEasyButtonActionPerformed
      EasyHighScoreTable easyLead = new EasyHighScoreTable(currentPlayer);
       easyLead.setVisible(true);
        dispose();
    }//GEN-LAST:event_jEasyButtonActionPerformed

    /**
     * Hard mode high scores
     * @param evt 
     */
    private void jHardModeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHardModeButtonActionPerformed
       HardHighScoreTable hardLead = new HardHighScoreTable(currentPlayer);
       hardLead.setVisible(true);
       dispose();
    }//GEN-LAST:event_jHardModeButtonActionPerformed

    /**
     * Main menu
     * @param evt 
     */
    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        Menu menu = new Menu(currentPlayer);
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel7MouseClicked
/**
 * Updates the Medium High Score table with the data from mediumArray.
 * It creates a new DefaultTableModel, adds columns, and populates the table with the data.
 */
        private void updateMediumHSTable() {
    // Create a new DefaultTableModel
    DefaultTableModel model = new DefaultTableModel();
    
    // Add columns to the model
    model.addColumn("User");
    model.addColumn("Top Highscores");
    
    // Add data from easyArray to the model
    for (int i = 0; i < mediumArray[0].length; i++) {
        model.addRow(new Object[]{mediumArray[0][i], mediumArray[1][i]});
    }
    
    // Set the new model to the jEasyModeHighScoreTable
    jMedModeHighScoreTable.setModel(model);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jEasyButton;
    private javax.swing.JButton jHardModeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton jMedButton;
    private javax.swing.JMenuBar jMedHighScoreMenuBar;
    private javax.swing.JTable jMedModeHighScoreTable;
    private javax.swing.JLabel jMedModeHighScoreTableLabel;
    private javax.swing.JMenu jMediumMenuBarLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
