package game;

/**
 * Packages used for Play class
 */
import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;
import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

/*
 * Play class runs the game
 * @author Hailey Pong
 */
public class Play extends javax.swing.JFrame {
    private Player player; 
    private int count;
    
    //public static Data data = Data.getInstance();
    /** * Variables used for game play */
    private int user_level;
    private int user_lives;
    private int user_scores;
    private String user_id;
    private String user_input;
    private int incorrect;

    /** * Variables used for UI display */

    private GamePlay user_game;
    
    private Boolean[] user_achievement;
    private int user_highscore;
    
    private String question;
    private String fact;
    
    /** Point incremented by for current level */
    private int increment;
    
    /**
     * Creates UI for game play and hides unnecessary UIs and initializes the user information/variables
     * @param player
     * @param game 
     */
    public Play(Player player, GamePlay game) {
        initComponents();

        newMedMess.setVisible(false);
        
        this.player = player;
        
        user_game = game;
        user_level = user_game.getLevel();        
        user_id = player.getId();
        user_highscore = player.getHighscore(user_level);
        user_achievement = player.getAchievement();
        user_scores = user_game.getScores();
        question = user_game.getCurrentQuestion();
        user_lives = user_game.getLives(user_level);
        increment = user_game.getPoints(user_level);
        incorrect = user_game.getIncorrect();        

        /** UI Display */
        correctUI.setVisible(false);
        overUI.setVisible(false);
        overUI.setVisible(false);
        gameSavingMess.setVisible(false);
        prevDisplay.setText(question);
        userID.setText(user_id);
        levelUI.setText("Level " + (user_level+1));        
        highscores.setText(user_highscore + " Highscore");
        gameLives.setText(""+incorrect);
        scores.setText(user_scores+" Points");
        heartDisplay();
        
        /** hard lives 3*/
        if (user_level == 2){
            life1.setVisible(false);
            life2.setVisible(false);
            life6.setVisible(false);
            life7.setVisible(false);
        }
        /** normal 5 */
        else if (user_level == 1){
            life1.setVisible(false);
            life7.setVisible(false);
        }

        /** easy 7 - do nothing */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameUI = new javax.swing.JPanel();
        gameLives = new javax.swing.JLabel();
        highscores = new javax.swing.JLabel();
        scores = new javax.swing.JLabel();
        previous = new javax.swing.JPanel();
        prevDisplay = new javax.swing.JLabel();
        inputAnswer = new javax.swing.JTextField();
        userID = new javax.swing.JLabel();
        levelUI = new javax.swing.JLabel();
        gameSavingMess = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        life1 = new javax.swing.JLabel();
        life2 = new javax.swing.JLabel();
        life3 = new javax.swing.JLabel();
        life4 = new javax.swing.JLabel();
        life5 = new javax.swing.JLabel();
        life6 = new javax.swing.JLabel();
        life7 = new javax.swing.JLabel();
        mainButton = new javax.swing.JLabel();
        correctUI = new javax.swing.JPanel();
        urCorrect = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        factsec = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nextButton = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        overUI = new javax.swing.JPanel();
        finishedGroup = new javax.swing.JPanel();
        finishedtitle = new javax.swing.JLabel();
        finishedPT = new javax.swing.JLabel();
        finishedLives = new javax.swing.JLabel();
        finishedHigh = new javax.swing.JLabel();
        finishedUser = new javax.swing.JLabel();
        levelUnlocked = new javax.swing.JLabel();
        overAchieve = new javax.swing.JButton();
        newMedMess = new javax.swing.JLabel();
        main = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        retry = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 600));

        gameUI.setBackground(new java.awt.Color(254, 253, 237));
        gameUI.setPreferredSize(new java.awt.Dimension(1020, 600));

        gameLives.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        gameLives.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameLives.setText("OOOOOO");

        highscores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        highscores.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        highscores.setText("Highscore");

        scores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        scores.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        scores.setText("0 Points");

        previous.setBackground(new java.awt.Color(255, 255, 255));
        previous.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        previous.setForeground(new java.awt.Color(255, 255, 255));

        prevDisplay.setBackground(new java.awt.Color(255, 255, 255));
        prevDisplay.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        prevDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prevDisplay.setText("Prev word");

        javax.swing.GroupLayout previousLayout = new javax.swing.GroupLayout(previous);
        previous.setLayout(previousLayout);
        previousLayout.setHorizontalGroup(
            previousLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(previousLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prevDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addContainerGap())
        );
        previousLayout.setVerticalGroup(
            previousLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(previousLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(prevDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        inputAnswer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        inputAnswer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enter(evt);
                ESC(evt);
            }
        });

        userID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        userID.setText("username");

        levelUI.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        levelUI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        levelUI.setText("Level");

        gameSavingMess.setBackground(new java.awt.Color(252, 52, 117));
        gameSavingMess.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        gameSavingMess.setForeground(new java.awt.Color(252, 68, 178));
        gameSavingMess.setText("Previous Chain was Saved in Slot");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Type Your Answer");

        jPanel1.setBackground(new java.awt.Color(254, 253, 237));

        life1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        life1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fullheart.png"))); // NOI18N

        life2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        life2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fullheart.png"))); // NOI18N

        life3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        life3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fullheart.png"))); // NOI18N

        life4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        life4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fullheart.png"))); // NOI18N

        life5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        life5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fullheart.png"))); // NOI18N

        life6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        life6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fullheart.png"))); // NOI18N

        life7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        life7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fullheart.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(life1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(life2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(life3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(life4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(life5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(life6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(life7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {life1, life2, life3, life4, life5, life6, life7});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(life2)
                    .addComponent(life3)
                    .addComponent(life4)
                    .addComponent(life5)
                    .addComponent(life6)
                    .addComponent(life1)
                    .addComponent(life7))
                .addContainerGap())
        );

        mainButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        mainButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout gameUILayout = new javax.swing.GroupLayout(gameUI);
        gameUI.setLayout(gameUILayout);
        gameUILayout.setHorizontalGroup(
            gameUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameUILayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(gameUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(previous, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(322, 322, 322))
            .addGroup(gameUILayout.createSequentialGroup()
                .addGroup(gameUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gameUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(gameUILayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(gameSavingMess, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(gameUILayout.createSequentialGroup()
                            .addGroup(gameUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(gameUILayout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addComponent(mainButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(userID, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(gameUILayout.createSequentialGroup()
                                    .addGap(344, 344, 344)
                                    .addGroup(gameUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(gameUILayout.createSequentialGroup()
                                            .addComponent(levelUI, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(86, 86, 86))))
                                .addGroup(gameUILayout.createSequentialGroup()
                                    .addGap(429, 429, 429)
                                    .addComponent(gameLives, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(161, 161, 161)
                            .addComponent(highscores, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                    .addGroup(gameUILayout.createSequentialGroup()
                        .addGap(825, 825, 825)
                        .addComponent(scores, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        gameUILayout.setVerticalGroup(
            gameUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameUILayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(gameUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameUILayout.createSequentialGroup()
                        .addGroup(gameUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(levelUI)
                            .addComponent(highscores, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scores, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(gameLives)
                        .addGap(27, 27, 27)
                        .addComponent(previous, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(153, 153, 153)
                        .addComponent(gameSavingMess)
                        .addGap(19, 19, 19))
                    .addGroup(gameUILayout.createSequentialGroup()
                        .addComponent(mainButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        correctUI.setBackground(new java.awt.Color(161, 195, 152));
        correctUI.setPreferredSize(new java.awt.Dimension(1000, 600));
        correctUI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                correctUIMouseClicked(evt);
            }
        });

        urCorrect.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        urCorrect.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        urCorrect.setText("ANSWER");

        factsec.setEditable(false);
        factsec.setBackground(new java.awt.Color(255, 255, 255));
        factsec.setColumns(20);
        factsec.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        factsec.setLineWrap(true);
        factsec.setRows(5);
        factsec.setText("A little over 8 million people live in New York City. That means 1 in every 38 people in the United States call the city home.\n");
        factsec.setWrapStyleWord(true);
        jScrollPane1.setViewportView(factsec);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("Click the screen to continue!");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Keep Going");

        nextButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/right-arrow.png"))); // NOI18N

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/crown.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star.png"))); // NOI18N

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/crown.png"))); // NOI18N

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fullheart.png"))); // NOI18N

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fullheart.png"))); // NOI18N

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fullheart.png"))); // NOI18N

        javax.swing.GroupLayout correctUILayout = new javax.swing.GroupLayout(correctUI);
        correctUI.setLayout(correctUILayout);
        correctUILayout.setHorizontalGroup(
            correctUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(correctUILayout.createSequentialGroup()
                .addGroup(correctUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, correctUILayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(160, 160, 160))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, correctUILayout.createSequentialGroup()
                        .addGroup(correctUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, correctUILayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel4)
                                .addGap(123, 123, 123)
                                .addGroup(correctUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(correctUILayout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(urCorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, correctUILayout.createSequentialGroup()
                                .addGap(330, 330, 330)
                                .addComponent(jLabel12)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(correctUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91))
            .addGroup(correctUILayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(219, 219, 219)
                .addComponent(jLabel11)
                .addGap(114, 114, 114)
                .addComponent(jLabel7))
        );
        correctUILayout.setVerticalGroup(
            correctUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(correctUILayout.createSequentialGroup()
                .addGroup(correctUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, correctUILayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(correctUILayout.createSequentialGroup()
                        .addGroup(correctUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(correctUILayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(correctUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(correctUILayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(72, 72, 72)))
                .addGroup(correctUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(correctUILayout.createSequentialGroup()
                        .addGroup(correctUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(correctUILayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7))
                            .addComponent(urCorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(correctUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(correctUILayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, correctUILayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101)))
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(correctUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, correctUILayout.createSequentialGroup()
                                .addComponent(nextButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, correctUILayout.createSequentialGroup()
                                .addGroup(correctUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)))
                        .addComponent(jLabel3)
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, correctUILayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))))
        );

        overUI.setBackground(new java.awt.Color(254, 253, 237));
        overUI.setPreferredSize(new java.awt.Dimension(1000, 600));

        finishedGroup.setBackground(new java.awt.Color(250, 112, 112));
        finishedGroup.setForeground(new java.awt.Color(255, 0, 0));

        finishedtitle.setBackground(new java.awt.Color(0, 0, 0));
        finishedtitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        finishedtitle.setForeground(new java.awt.Color(255, 255, 255));
        finishedtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        finishedtitle.setText("YOU LOSE");

        finishedPT.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        finishedPT.setForeground(new java.awt.Color(255, 255, 255));
        finishedPT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        finishedPT.setText("Points");

        finishedLives.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        finishedLives.setForeground(new java.awt.Color(255, 255, 255));
        finishedLives.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        finishedLives.setText("Lives Left");

        finishedHigh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        finishedHigh.setForeground(new java.awt.Color(255, 255, 255));
        finishedHigh.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        finishedHigh.setText("Highscore");

        finishedUser.setBackground(new java.awt.Color(255, 255, 255));
        finishedUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        finishedUser.setForeground(new java.awt.Color(255, 255, 255));
        finishedUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        finishedUser.setText("username");

        javax.swing.GroupLayout finishedGroupLayout = new javax.swing.GroupLayout(finishedGroup);
        finishedGroup.setLayout(finishedGroupLayout);
        finishedGroupLayout.setHorizontalGroup(
            finishedGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(finishedGroupLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(finishedUser, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, finishedGroupLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(finishedtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, finishedGroupLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(finishedGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(finishedHigh, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finishedLives, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finishedPT, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101))
        );
        finishedGroupLayout.setVerticalGroup(
            finishedGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(finishedGroupLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(finishedtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(finishedUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(finishedPT, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finishedLives, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finishedHigh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        levelUnlocked.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        levelUnlocked.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        levelUnlocked.setText("Now you can proceed to the next level!");

        overAchieve.setBackground(new java.awt.Color(250, 112, 112));
        overAchieve.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        overAchieve.setForeground(new java.awt.Color(255, 255, 255));
        overAchieve.setText("Achievements");
        overAchieve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overAchieveButton(evt);
            }
        });

        newMedMess.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        newMedMess.setForeground(new java.awt.Color(255, 102, 102));
        newMedMess.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        newMedMess.setText("New Medal Unlocked!");

        main.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        main.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        main.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainMouseClicked(evt);
            }
        });

        jLabel13.setText("Back to Menu");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fullheart.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fullheart.png"))); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fullheart.png"))); // NOI18N

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fullheart.png"))); // NOI18N

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star.png"))); // NOI18N

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star.png"))); // NOI18N

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star.png"))); // NOI18N

        retry.setBackground(new java.awt.Color(255, 102, 102));
        retry.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        retry.setForeground(new java.awt.Color(255, 255, 255));
        retry.setText("RETRY?");
        retry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retryActionPerformed(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fullheart.png"))); // NOI18N

        javax.swing.GroupLayout overUILayout = new javax.swing.GroupLayout(overUI);
        overUI.setLayout(overUILayout);
        overUILayout.setHorizontalGroup(
            overUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overUILayout.createSequentialGroup()
                .addGroup(overUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(overUILayout.createSequentialGroup()
                        .addGroup(overUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(overUILayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(overUILayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel13))
                            .addGroup(overUILayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(overUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel14))))
                        .addGap(214, 214, 214))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, overUILayout.createSequentialGroup()
                        .addGroup(overUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel15))
                        .addGap(84, 84, 84)))
                .addGroup(overUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(overUILayout.createSequentialGroup()
                        .addGroup(overUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(finishedGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(levelUnlocked, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, overUILayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(70, 70, 70)))
                        .addGroup(overUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(overUILayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                                .addGroup(overUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, overUILayout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(96, 96, 96))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, overUILayout.createSequentialGroup()
                                        .addGroup(overUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17)
                                            .addGroup(overUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(newMedMess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(overAchieve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(24, 24, 24))))
                            .addGroup(overUILayout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jLabel19)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(overUILayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(retry)
                        .addContainerGap())))
        );
        overUILayout.setVerticalGroup(
            overUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overUILayout.createSequentialGroup()
                .addGroup(overUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(overUILayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(overUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(overAchieve, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(main))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(overUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newMedMess)
                            .addComponent(jLabel13)))
                    .addGroup(overUILayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel21)))
                .addGroup(overUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(overUILayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel16)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel19))
                    .addGroup(overUILayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel14))
                    .addGroup(overUILayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(overUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(overUILayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(193, 193, 193)
                                .addComponent(jLabel15))
                            .addComponent(finishedGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(overUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(overUILayout.createSequentialGroup()
                        .addComponent(levelUnlocked, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(retry, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, overUILayout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addGroup(overUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, overUILayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(83, 83, 83))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, overUILayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(82, 82, 82))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(correctUI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(overUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gameUI, javax.swing.GroupLayout.PREFERRED_SIZE, 991, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(overUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(correctUI, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE))
                .addGap(584, 584, 584))
            .addGroup(layout.createSequentialGroup()
                .addComponent(gameUI, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        correctUI.getAccessibleContext().setAccessibleName("");

        setSize(new java.awt.Dimension(1000, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
        
    /**
     * Submits the answer when enter key is pressed
     * @param evt 
     */
    private void enter(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enter
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            user_input = inputAnswer.getText();
            chain(); 
        }
    }//GEN-LAST:event_enter

 
    /**
     * Back to game play when clicked 
     * @param evt 
     */
    private void correctUIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_correctUIMouseClicked
            hideCorrectUI();
            prevDisplay.setText(question);
            inputAnswer.setText("");
            gameUI.setVisible(true);
    }//GEN-LAST:event_correctUIMouseClicked

    /** 
     * Opens achievement button
     * @param evt 
     */
    private void overAchieveButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overAchieveButton
        Achievement achievement = new Achievement(player);
        achievement.setVisible(true);
        dispose();
    }//GEN-LAST:event_overAchieveButton

    private void mainButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainButtonMouseClicked
        Menu main = new Menu(player);
        main.setVisible(true);
        dispose();
    }//GEN-LAST:event_mainButtonMouseClicked

    /** returns to main
     * 
     * @param evt 
     */
    private void mainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainMouseClicked
        Menu main = new Menu(player);
        main.setVisible(true);
        dispose();
    }//GEN-LAST:event_mainMouseClicked

    /**
     * play again
     * @param evt 
     */
    private void retryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retryActionPerformed
        GamePlay newGame = new GamePlay(user_level);
        Play play = new Play(player,newGame);
        play.setVisible(true);
        dispose();
    }//GEN-LAST:event_retryActionPerformed

    /**
     * ESC - main menu
     * @param evt 
     */
    private void ESC(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ESC
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {    
            Menu main = new Menu(player);
            main.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_ESC

    public class playMusicJava { // method that initializes the sound file path for incorrect sound
        public static void main (String[] args) {
            String filepath = "Incorrect Sound.wav";
            playMusic(filepath);
        }
    }

    public static void playMusic(String location) 
    {
        try
        {
        File musicPath = new File(location);
           
        if(musicPath.exists())
        {
            AudioInputStream audioInput = AudioSystem.getAudioInputStream(musicPath);
            Clip clip = AudioSystem.getClip();
            clip.open(audioInput);
            clip.start();
        }
        else
        
        {
            System.out.println("Can't find the file"); // prints file not found 
        }   
    }
    catch (Exception e) 
    {
        System.out.println(e);
    }
} 
    public class playMusic1Java { // method that initializes the sound file path for incorrect sound
        public static void main (String[] args) {
            String filepath = "Correct Sound.wav";
            playMusic(filepath);
        }
    }
    
    public static void playMusic1(String location) 
    {
        
        try
        {
        File musicPath = new File(location);
           
        if(musicPath.exists())
        {
            AudioInputStream audioInput = AudioSystem.getAudioInputStream(musicPath);
            Clip clip = AudioSystem.getClip();
            clip.open(audioInput);
            clip.start();
        }
        else     
        {
            System.out.println("Can't find the file"); //prints file not found
        }
        
    }

    catch (Exception e)
    {
        System.out.println(e);
    }
}

    /**
     * Checks if the user input correct answer and decrement/increment points according the answer
     * 
     * Updates user's high score if the user breaks their record
     */
    private void chain(){
        Boolean check = user_game.checkAns(question,user_input);
        
        /** Incorrect Answer */
        if (!check) {
            
            playMusic("Incorrect Sound.wav"); // plays incorrect sound noise for each incorrect answer 
            user_scores -= 2;
            incorrect --;
            scores.setText(user_scores + " Points");
            //scores.setColor;
            jLabel2.setText("Incorrect! Try Again!");
            gameUI.setBackground(new java.awt.Color(250, 112, 112));     
            jPanel1.setBackground(new java.awt.Color(250, 112, 112));
            gameLives.setText("" + incorrect);
            heartDisplay();
        }        
        /** Correct Answer */
        if (check) {

            playMusic("Correct Sound.wav"); // plays correct sound noise for each correct answer 
            hideGameUI();
            question = user_input;    
            user_scores = user_scores + increment;
            scores.setText(user_scores + " Points");
            jLabel2.setText("Type Your Answer!");            
            correctUI.setVisible(true);
            fact = user_game.getFact(user_input);
            urCorrect.setText(user_input);
            factsec.setText(fact);
            question = user_input;    
            //original color
            jPanel1.setBackground(new java.awt.Color(254, 253, 237));
            gameUI.setBackground(new java.awt.Color(254, 253, 237));
        }
  
        /** Update high score */
        if (user_highscore < user_scores) {
            user_highscore = user_scores;
            highscores.setText(user_highscore + " Highscore");
            player.setHighscore(user_level, user_highscore);
        }
        
        /** Game Over */
        if (incorrect <= 0 && user_scores < 100) {
            hideGameUI();
            hideCorrectUI();
            finishedtitle.setText("YOU LOSE");
            finishedUser.setText(user_id);
            finishedPT.setText(user_scores + " POINTS");
            finishedLives.setText(incorrect + " Lives Left");
            finishedHigh.setText(user_highscore + " Highscore");
            levelUnlocked.setText("Try Again...");
            // panel color            
            finishedGroup.setBackground(new java.awt.Color(250, 112, 112));
            overUI.setVisible(true);
        }
        
        /** Game Completed */
        else if (incorrect > 0 && user_scores >= 100){
            hideGameUI();
            hideCorrectUI();
            finishedtitle.setText("LEVEL COMPLETED");
            finishedUser.setText(user_id);
            finishedPT.setText(user_scores + " POINTS");
            finishedLives.setText(incorrect + " Lives Left");
            finishedHigh.setText(user_highscore + " Highscore");
            
            if (player.getProg() <=2 ) {
                levelUnlocked.setText("You can proceed to next level!" );                            
            }
            else if (player.getProg() == 3) {
                levelUnlocked.setText("You have completed all the levels!");
            }
            
            // panel color
            finishedGroup.setBackground(new java.awt.Color(153, 102, 255));
            
            /** Unlock next level */
            overUI.setVisible(true);
            player.setProg(user_level+1);
            player.setLevelsCompleted(user_level,true);

            /** No wrong answers */
            Boolean temp[] = player.getAchievement();
            if (incorrect == user_lives && !temp[user_level]) {
                newMedMess.setVisible(false);
                player.setAchievement(user_level);
                newMedMess.setVisible(true);
            }
        }
        
        /** automatically save the game */        
        saveGame(question);
    }
    
/** Save Game in CSV*/
    private void saveGame(String chain){
        user_game.saveGame(user_level, user_scores, chain, incorrect);
        user_game.saveToCSV(user_id, user_level);
        Player newData = new Player(user_id,0, player.getHighscore(), player.getProg(),player.getAchievement());
        Data.getInstance().retrieveData();
        Data.getInstance().addPlayer(newData);
        Data.getInstance().removeDup();
        Data.getInstance().updateData();        

        gameSavingMess.setText("Previous Chain was Saved in Slot " + (user_level+1));
        gameSavingMess.setVisible(true);
    }
    
    /** lives display */
    private void heartDisplay(){
        
        if (user_level == 0) {
            if (incorrect <= 6){
                life1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png")));
            } if (incorrect <= 5){
                life2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png")));                
            } if (incorrect <= 4){
                life3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png")));                
            } if (incorrect <= 3){
                life3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png")));
                life4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png")));
            } if (incorrect <= 2){
                life5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png")));                
            } if (incorrect <= 1){
                life6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png")));                
            } if (incorrect <= 0) {
                life7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png")));                
            }            
        } else if (user_level == 1){
           } if (incorrect <= 4){
                life2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png")));                
            } if (incorrect <= 3){
                life3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png")));                
            } if (incorrect <= 2){
                life4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png")));
            } if (incorrect <= 1){
                life5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png")));                
            } if (incorrect <= 0){
                life6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png")));                
        } else if (user_level == 2) {
            } if (incorrect == 3) {
                      life3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fullheart.png")));          
                } 
            if (incorrect <= 2){
                life3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png")));
            } if (incorrect <= 1){
                life4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png")));                
            } if (incorrect <= 0){
                life5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png")));               
        }      
   }
    
    /** Hide Game UI */
    private void hideGameUI(){
        gameUI.setVisible(false);
    }
    
    /** Hide Correct UI */    
    private void hideCorrectUI(){
        correctUI.setVisible(false);
    }
    
                
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel correctUI;
    private javax.swing.JTextArea factsec;
    private javax.swing.JPanel finishedGroup;
    private javax.swing.JLabel finishedHigh;
    private javax.swing.JLabel finishedLives;
    private javax.swing.JLabel finishedPT;
    private javax.swing.JLabel finishedUser;
    private javax.swing.JLabel finishedtitle;
    private javax.swing.JLabel gameLives;
    private javax.swing.JLabel gameSavingMess;
    private javax.swing.JPanel gameUI;
    private javax.swing.JLabel highscores;
    private javax.swing.JTextField inputAnswer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel levelUI;
    private javax.swing.JLabel levelUnlocked;
    private javax.swing.JLabel life1;
    private javax.swing.JLabel life2;
    private javax.swing.JLabel life3;
    private javax.swing.JLabel life4;
    private javax.swing.JLabel life5;
    private javax.swing.JLabel life6;
    private javax.swing.JLabel life7;
    private javax.swing.JLabel main;
    private javax.swing.JLabel mainButton;
    private javax.swing.JLabel newMedMess;
    private javax.swing.JLabel nextButton;
    private javax.swing.JButton overAchieve;
    private javax.swing.JPanel overUI;
    private javax.swing.JLabel prevDisplay;
    private javax.swing.JPanel previous;
    private javax.swing.JButton retry;
    private javax.swing.JLabel scores;
    private javax.swing.JLabel urCorrect;
    private javax.swing.JLabel userID;
    // End of variables declaration//GEN-END:variables
}
